Add want subcommand

diff --git a/opt/bin/config b/opt/bin/config
--- a/opt/bin/config
+++ b/opt/bin/config
@@ -5,6 +5,7 @@ set -o pipefail
 
 repo_base="$HOME/.dot"
 news="$HOME/.config/.news"
+meta="$HOME/.config/.meta"
 
 function list_repos
 {
@@ -58,6 +59,8 @@ function clone_repo
 	git clone --bare $uri $repo_path
 	$0 $name config status.showUntrackedFiles no
 	$0 $name checkout
+  mkdir -p ${HOME}/.config/${name}/hooks
+  $0 $name config --add core.hookspath ${HOME}/.config/${name}/hooks
 }
 
 function init_repo
@@ -102,6 +105,24 @@ function owner
 	done
 }
 
+function want
+{
+	set +e
+
+	for f in $(ls ${meta}/want/*); do
+		wants=($(cat $f))
+		for line in ${wants[@]}; do
+			hash ${line} 2>/dev/null || (
+				if [ $profile_shown -eq 0 ]; then
+					echo "$(basename $f):"
+					profile_shown=1
+				fi
+				echo "  missing: $line")
+		done
+		profile_shown=0
+	done
+}
+
 function usage
 {
 	cat <<-EOU
@@ -117,6 +138,7 @@ function usage
 		    "clone": clone a repo into the config system
 		    "init" : create a skeleton repo
 		    "owner" : pass a file and be told which of the config repos it is managed by
+		    "want" : list software that various usage profiles want
 		    "*"    : passed to git
 
 		  examples:
@@ -127,6 +149,7 @@ function usage
 		    config init <name>
 		    config owner zsh/function/blah
 		    config status
+		    config want
 		    config <repo> log
 	EOU
 }
@@ -180,6 +203,11 @@ case $1 in
 	"owner")
 		shift;
 		owner $@
+		exit
+		;;
+	"want")
+		shift;
+		want $@
 		exit
 		;;
 esac
